### ISSUE TITLE
password for baidu pan

### ISSUE THREAD

**Issue by FeiTeacher** [SYSU-DISG/AVoiD-DF#3]

**Comment by FeiTeacher** [comment]
Can you share the password.thank you very much.

**Comment by RedamancyAY** [comment]
So, have you got the password?

**Comment by SYSU-DISG** [comment]
Please contact the first author by email for relevant information

**Comment by SYSU-DISG** [comment]
Sorry, due to protocol restrictions, the dataset is not publicly available.
